name: core device emulator

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Prepare Nix ARTIQ environment
        run: nix build --accept-flake-config .github/artiq-emulator#devShells.x86_64-linux.default
      - name: Run unit tests with core device emulator
        run: ARTIQ_ROOT=$GITHUB_WORKSPACE/.github/artiq-emulator nix develop --accept-flake-config .github/artiq-emulator#devShells.x86_64-linux.default --command python -m unittest discover -v test